
window.BIBLE_BOOKS = {
    "genesis": "창세기", "exodus": "출애굽기", "leviticus": "레위기", "numbers": "민수기", "deuteronomy": "신명기",
    "joshua": "여호수아", "judges": "사사기", "ruth": "룻기", "samuel1": "사무엘상", "samuel2": "사무엘하",
    "kings1": "열왕기상", "kings2": "열왕기하", "chronicles1": "역대상", "chronicles2": "역대하", "ezra": "에스라",
    "nehemiah": "느헤미야", "esther": "에스더", "job": "욥기", "psalms": "시편", "proverbs": "잠언",
    "ecclesiastes": "전도서", "songofsongs": "아가", "isaiah": "이사야", "jeremiah": "예레미야", "lamentations": "예레미야애가",
    "ezekiel": "에스겔", "daniel": "다니엘", "hosea": "호세아", "joel": "요엘", "amos": "아모스",
    "obadiah": "오바댜", "jonah": "요나", "micah": "미가", "nahum": "나훔", "habakkuk": "하박국",
    "zephaniah": "스바냐", "haggai": "학개", "zechariah": "스가랴", "malachi": "말라기", "matthew": "마태복음",
    "mark": "마가복음", "luke": "누가복음", "john": "요한복음", "acts": "사도행전", "romans": "로마서",
    "1corinthians": "고린도전서", "corinthians2": "고린도후서", "galatians": "갈라디아서", "ephesians": "에베소서", "philippians": "빌립보서",
    "colossians": "골로새서", "thessalonians1": "데살로니가전서", "thessalonians2": "데살로니가후서", "timothy1": "디모데전서", "timothy2": "디모데후서",
    "titus": "디도서", "philemon": "빌레몬서", "hebrews": "히브리서", "james": "야고보서", "peter1": "베드로전서",
    "peter2": "베드로후서", "john1": "요한1서", "john2": "요한2서", "john3": "요한3서", "jude": "유다서", "revelation": "요한계시록"
};

window.BIBLE_ABBREVIATIONS = {
    "창": "genesis", "창세기": "genesis", "gen": "genesis", "gn": "genesis",
    "출": "exodus", "출애굽기": "exodus", "exo": "exodus", "ex": "exodus",
    "레": "leviticus", "레위기": "leviticus", "lev": "leviticus", "lv": "leviticus",
    "민": "numbers", "민수기": "numbers", "num": "numbers", "nm": "numbers",
    "신": "deuteronomy", "신명기": "deuteronomy", "deu": "deuteronomy", "dt": "deuteronomy",
    "수": "joshua", "여호수아": "joshua", "jos": "joshua", "jsh": "joshua",
    "삿": "judges", "사사기": "judges", "jdg": "judges", "jg": "judges",
    "룻": "ruth", "룻기": "ruth", "ru": "ruth",
    "삼상": "samuel1", "사무엘상": "samuel1", "1sa": "samuel1", "1s": "samuel1",
    "삼하": "samuel2", "사무엘하": "samuel2", "2sa": "samuel2", "2s": "samuel2",
    "왕상": "kings1", "열왕기상": "kings1", "1ki": "kings1", "1k": "kings1",
    "왕하": "kings2", "열왕기하": "kings2", "2ki": "kings2", "2k": "kings2",
    "대상": "chronicles1", "역대상": "chronicles1", "1ch": "chronicles1", "1c": "chronicles1",
    "대하": "chronicles2", "역대하": "chronicles2", "2ch": "chronicles2", "2c": "chronicles2",
    "스": "ezra", "에스라": "ezra", "ezr": "ezra",
    "느": "nehemiah", "느헤미야": "nehemiah", "neh": "nehemiah",
    "에": "esther", "에스더": "esther", "est": "esther",
    "욥": "job", "욥기": "job",
    "시": "psalms", "시편": "psalms", "psa": "psalms", "ps": "psalms",
    "잠": "proverbs", "잠언": "proverbs", "pro": "proverbs", "prv": "proverbs",
    "전": "ecclesiastes", "전도서": "ecclesiastes", "ecc": "ecclesiastes", "ec": "ecclesiastes",
    "아": "songofsongs", "아가": "songofsongs", "sng": "songofsongs", "ss": "songofsongs",
    "사": "isaiah", "이사야": "isaiah", "isa": "isaiah",
    "렘": "jeremiah", "예레미야": "jeremiah", "jer": "jeremiah",
    "애": "lamentations", "예레미야애가": "lamentations", "lam": "lamentations",
    "겔": "ezekiel", "에스겔": "ezekiel", "ezk": "ezekiel",
    "단": "daniel", "다니엘": "daniel", "dan": "daniel",
    "호": "hosea", "호세아": "hosea", "hos": "hosea",
    "욜": "joel", "요엘": "joel", "jl": "joel",
    "암": "amos", "아모스": "amos", "am": "amos",
    "옵": "obadiah", "오바댜": "obadiah", "oba": "obadiah",
    "욘": "jonah", "요나": "jonah", "jon": "jonah",
    "미": "micah", "미가": "micah", "mic": "micah",
    "나": "nahum", "나훔": "nahum", "na": "nahum",
    "합": "habakkuk", "하박국": "habakkuk", "hab": "habakkuk",
    "습": "zephaniah", "스바냐": "zephaniah", "zep": "zephaniah", "zp": "zephaniah",
    "학": "haggai", "학개": "haggai", "hag": "haggai",
haggai",
    "슥": "zechariah", "스가랴": "zechariah", "zec": "zechariah",
    "말": "malachi", "말라기": "malachi", "mal": "malachi",
    "마": "matthew", "마태복음": "matthew", "mat": "matthew", "mt": "matthew",
    "막": "mark", "마가복음": "mark", "mrk": "mark", "mk": "mark",
    "눅": "luke", "누가복음": "luke", "luk": "luke", "lk": "luke",
    "요": "john", "요한복음": "john", "jhn": "john", "jn": "john",
    "행": "acts", "사도행전": "acts", "act": "acts",
    "롬": "romans", "로마서": "romans", "rom": "romans",
    "고전": "1corinthians", "고린도전서": "1corinthians", "1co": "1corinthians",
    "고후": "corinthians2", "고린도후서": "corinthians2", "2co": "corinthians2",
    "갈": "galatians", "갈라디아서": "galatians", "gal": "galatians",
    "엡": "ephesians", "에베소서": "ephesians", "eph": "ephesians",
    "빌": "philippians", "빌립보서": "philippians", "php": "philippians",
    "골": "colossians", "골로새서": "colossians", "col": "colossians",
    "살전": "thessalonians1", "데살로니가전서": "thessalonians1", "1th": "thessalonians1",
    "살후": "thessalonians2", "데살로니가후서": "thessalonians2", "2th": "thessalonians2",
    "딤전": "timothy1", "디모데전서": "timothy1", "1ti": "timothy1",
    "딤후": "timothy2", "디모데후서": "timothy2", "2ti": "timothy2",
    "딛": "titus", "디도서": "titus", "tit": "titus",
    "몬": "philemon", "빌레몬서": "philemon", "phm": "philemon",
    "히": "hebrews", "히브리서": "hebrews", "heb": "hebrews",
    "약": "james", "야고보서": "james", "jas": "james",
    "벧전": "peter1", "베드로전서": "peter1", "1pe": "peter1",
    "벧후": "peter2", "베드로후서": "peter2", "2pe": "peter2",
    "요일": "john1", "요한1서": "john1", "1jn": "john1",
    "요이": "john2", "요한2서": "john2", "2jn": "john2",
    "요삼": "john3", "요한3서": "john3", "3jn": "john3",
    "유": "jude", "유다서": "jude",
    "계": "revelation", "요한계시록": "revelation", "rev": "revelation"
};
